from aligntune.src.nn.gemma import (
    PaliGemmaForConditionalGeneration,
    PaliGemmaConfig,
)
from transformers import AutoTokenizer
import json
import glob
from safetensors import safe_open
from typing import Tuple
import os

lora_target_modules = [
    "vision_tower.vision_model.encoder.layers.0.self_attn.v_proj",
    "vision_tower.vision_model.encoder.layers.0.self_attn.q_proj",
    "vision_tower.vision_model.encoder.layers.1.self_attn.v_proj",
    "vision_tower.vision_model.encoder.layers.1.self_attn.q_proj",
    "vision_tower.vision_model.encoder.layers.2.self_attn.v_proj",
    "vision_tower.vision_model.encoder.layers.2.self_attn.q_proj",
    "vision_tower.vision_model.encoder.layers.3.self_attn.v_proj",
    "vision_tower.vision_model.encoder.layers.3.self_attn.q_proj",
    "vision_tower.vision_model.encoder.layers.4.self_attn.v_proj",
    "vision_tower.vision_model.encoder.layers.4.self_attn.q_proj",
    "vision_tower.vision_model.encoder.layers.5.self_attn.v_proj",
    "vision_tower.vision_model.encoder.layers.5.self_attn.q_proj",
    "vision_tower.vision_model.encoder.layers.6.self_attn.v_proj",
    "vision_tower.vision_model.encoder.layers.6.self_attn.q_proj",
    "vision_tower.vision_model.encoder.layers.7.self_attn.v_proj",
    "vision_tower.vision_model.encoder.layers.7.self_attn.q_proj",
    "vision_tower.vision_model.encoder.layers.8.self_attn.v_proj",
    "vision_tower.vision_model.encoder.layers.8.self_attn.q_proj",
    "vision_tower.vision_model.encoder.layers.9.self_attn.v_proj",
    "vision_tower.vision_model.encoder.layers.9.self_attn.q_proj",
    "vision_tower.vision_model.encoder.layers.10.self_attn.v_pro",
    "vision_tower.vision_model.encoder.layers.10.self_attn.q_pro",
    "vision_tower.vision_model.encoder.layers.11.self_attn.v_pro",
    "vision_tower.vision_model.encoder.layers.11.self_attn.q_pro",
    "vision_tower.vision_model.encoder.layers.12.self_attn.v_pro",
    "vision_tower.vision_model.encoder.layers.12.self_attn.q_pro",
    "vision_tower.vision_model.encoder.layers.13.self_attn.v_pro",
    "vision_tower.vision_model.encoder.layers.13.self_attn.q_pro",
    "vision_tower.vision_model.encoder.layers.14.self_attn.v_pro",
    "vision_tower.vision_model.encoder.layers.14.self_attn.q_pro",
    "vision_tower.vision_model.encoder.layers.15.self_attn.v_pro",
    "vision_tower.vision_model.encoder.layers.15.self_attn.q_pro",
    "vision_tower.vision_model.encoder.layers.16.self_attn.v_pro",
    "vision_tower.vision_model.encoder.layers.16.self_attn.q_pro",
    "vision_tower.vision_model.encoder.layers.17.self_attn.v_pro",
    "vision_tower.vision_model.encoder.layers.17.self_attn.q_pro",
    "vision_tower.vision_model.encoder.layers.18.self_attn.v_pro",
    "vision_tower.vision_model.encoder.layers.18.self_attn.q_pro",
    "vision_tower.vision_model.encoder.layers.19.self_attn.v_pro",
    "vision_tower.vision_model.encoder.layers.19.self_attn.q_pro",
    "vision_tower.vision_model.encoder.layers.20.self_attn.v_pro",
    "vision_tower.vision_model.encoder.layers.20.self_attn.q_pro",
    "vision_tower.vision_model.encoder.layers.21.self_attn.v_pro",
    "vision_tower.vision_model.encoder.layers.21.self_attn.q_pro",
    "vision_tower.vision_model.encoder.layers.22.self_attn.v_pro",
    "vision_tower.vision_model.encoder.layers.22.self_attn.q_pro",
    "vision_tower.vision_model.encoder.layers.23.self_attn.v_pro",
    "vision_tower.vision_model.encoder.layers.23.self_attn.q_pro",
    "vision_tower.vision_model.encoder.layers.24.self_attn.v_pro",
    "vision_tower.vision_model.encoder.layers.24.self_attn.q_pro",
    "vision_tower.vision_model.encoder.layers.25.self_attn.v_pro",
    "vision_tower.vision_model.encoder.layers.25.self_attn.q_pro",
    "vision_tower.vision_model.encoder.layers.26.self_attn.v_pro",
    "vision_tower.vision_model.encoder.layers.26.self_attn.q_pro",
]
